---
Name: mysite-project
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SilverStripe\View\SSViewer:
  themes:
    - simple
    - '$default'
  theme_enabled: true
Symbiote\Multisites\Model\Site:
  available_themes:
    - simple
---
Name: mysite-db
---
SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4
  connection_collation: utf8mb4_unicode_ci
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
---
Name: mysite-errors
Only:
  environment: dev
---
SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      LogFileHandler: [ pushHandler, [ %$LogFileHandler ] ]
  LogFileHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      - "mysite/silverstripe.log"
      - "info"
