---
Name: mysite-project
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SilverStripe\View\SSViewer:
  theme: simple
---
Name: mysite-errors
Only:
  environment: dev
---
SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      LogFileHandler: [ pushHandler, [ %$LogFileHandler ] ]
  LogFileHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      - "mysite/silverstripe.log"
      - "info"
